name: 'Github Release Action'
description: 'Creates a new Github release and optionally uploads an artifact'
author: 'MobilePossse'
inputs:
  repo_token:
    description: 'The GITHUB_TOKEN secret'
  version:
    description: 'Version number to use for the release tag'
  filename:
    description: 'Name of the file to attach to the release'
runs:
  using: 'node12'
  main: 'lib/index.js'
